name: build-and-test-app

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    runs-on: [self-hosted, macOS]
    steps:
      - uses: actions/checkout@v2

      # Uncomment to run static code analysis
      # - name: Check static code quality of iOS App
      #   run: eval "$(/opt/homebrew/bin/rbenv init - --no-rehash bash)" && bundle exec fastlane swift_lint

      # Uncomment to run tests
      # - name: Run Unit and UI Tests
        # run: eval "$(/opt/homebrew/bin/rbenv init - --no-rehash bash)" && bundle exec fastlane test

      - name: Install Gems
        run: |
          eval "$(/opt/homebrew/bin/rbenv init - --no-rehash bash)"
          cd EducationalGame
          bundle install 

      - name: Generate build number
        run: |
          # Build number is current date/time in format YYYYMMDDHHMMSS
          BUILD_NUMBER=$(date +'%Y%m%d%H%M%S')
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - name: Build iOS App
        run: |
          eval "$(/opt/homebrew/bin/rbenv init - --no-rehash bash)"
          cd EducationalGame
          bundle exec fastlane build
        env:
          MATCH_GITLAB_AUTH: ${{ secrets.IOS_MATCH_GITLAB_AUTH }}
          MATCH_PASSWORD: ${{ secrets.IOS_MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ vars.IOS_MATCH_GIT_URL }}
          API_KEY_ID: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY_KEY_ID }}
          API_KEY_ISSUER_ID: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          API_KEY_PASSWORD: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY_PASSWORD }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: /opt/actions-runner/_work/artemis-ios/artemis-ios/build/App.ipa